import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import ProductLayout from "layout/product";

// Pre-render (Static) => CSR

export default function Home({ description, heroID, villainID, seos }) {
  const [state, setState] = useState();
  const router = useRouter();
  const { isFallback } = router;

  const getData = async () => {
    const resp = await fetch("https://demo-be-thrive.herokuapp.com/products");
    const data = await resp.json();
    console.log({ data });
    const description = data[0]?.description;
    setState(description);
  };

  useEffect(() => {
    getData();
  }, []);

  useEffect(() => {
    console.log("ini pure dari client", state);
  }, [state]);

  if (isFallback) {
    return <h1>Lagi loading bro...</h1>;
  }

  return (
    <ProductLayout seos={seos}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <h1>{description}</h1>
          <h1>{heroID}</h1>
          <h1>{villainID}</h1>
          <h1>{state}</h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </ProductLayout>
  );
}

export async function getStaticPaths() {
  const resp = await fetch("https://demo-be-thrive.herokuapp.com/products");
  const data = await resp.json();

  const allPaths = data.map((product) => ({ params: { id: `${product.id}` } }));

  return {
    paths: allPaths,
    fallback: false, // false or 'blocking'
  };
}

// build time => setiap kali kita ngebuild app
// request time => setiap kali user melakukan request halaman

export async function getStaticProps(context) {
  const { query, params } = context;
  const resp = await fetch(
    `https://demo-be-thrive.herokuapp.com/products?id=${params.id}`
  );
  const data = await resp.json();
  const description = data[0]?.description;
  const heroID = query?.hero || 0;
  const villainID = query?.villain || 0;
  const requiredData = data[0];
  const seos = {
    title: requiredData.title,
    description: requiredData.description,
    author: "Alta Thrive",
    keywords: requiredData.title,
    canonicalUrl: `https://demo-seo-thrive.vercel.app/ssg/${params.id}`,
    ogTitle: requiredData.title,
    ogDescription: requiredData.description,
    ogImageUrl: `https://demo-be-thrive.herokuapp.com${requiredData.image.url}`,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogType: "product",
    ogUrl: `https://demo-seo-thrive.vercel.app/ssg/${params.id}`,
    twitterCard: "summary",
    twitterTitle: requiredData.title,
    twitterDescription: requiredData.description,
    twitterUrl: `https://demo-seo-thrive.vercel.app/ssg/${params.id}`,
  };

  return {
    props: {
      description,
      heroID,
      villainID,
      seos,
    }, // will be passed to the page component as props
    revalidate: 5,
  };
}
