import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

// Pre-render (Static) => CSR

export default function Home({ description, heroID, villainID }) {
  const [state, setState] = useState();

  const getData = async () => {
    const resp = await fetch("https://demo-be-thrive.herokuapp.com/products");
    const data = await resp.json();
    console.log({ data });
    const description = data[0]?.description;
    setState(description);
  };

  useEffect(() => {
    getData();
  }, []);

  useEffect(() => {
    console.log("ini pure dari client", state);
  }, [state]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>{description}</h1>
        <h1>{heroID}</h1>
        <h1>{villainID}</h1>
        <h1>{state}</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// build time => setiap kali kita ngebuild app
// request time => setiap kali user melakukan request halaman

export async function getStaticProps(context) {
  // SSR
  const { query } = context;
  console.log({ query });
  // SSR
  const resp = await fetch("https://demo-be-thrive.herokuapp.com/products");
  const data = await resp.json();
  const description = data[0]?.description;
  const heroID = query?.hero || 0;
  const villainID = query?.villain || 0;

  console.log("ini dari SSG", description);

  return {
    props: {
      description,
      heroID,
      villainID,
    }, // will be passed to the page component as props
    revalidate: 5,
  };
}
